// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthWindProject.Application.Common.Access;

namespace NorthWind.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220731102521_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("NorthWind.Core.Entities.Car.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("About")
                        .HasColumnType("longtext");

                    b.Property<string>("CarModels")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "ООО \"Северный Ветер\" предлагает услуги работы КДМ с оператором.",
                            CarModels = "[{\"Indicator\":\"Модель шасси\",\"Parameter\":\"КАМАЗ-65115\"},{\"Indicator\":\"Масса машины полная, кг\",\"Parameter\":\"22400\"},{\"Indicator\":\"Ширина рабочей зоны, м (при мойке)\",\"Parameter\":\"8,5\"},{\"Indicator\":\"Ширина рабочей зоны, м (при мойке)\",\"Parameter\":\"8,5\"},{\"Indicator\":\"Ширина рабочей зоны, м (при поливке)\",\"Parameter\":\"20,0\"},{\"Indicator\":\"Ширина рабочей зоны, м (плуга)\",\"Parameter\":\"2,5\"},{\"Indicator\":\"Ширина рабочей зоны, м (щетки)\",\"Parameter\":\"2,3\"},{\"Indicator\":\"Рабочее давление воды, МПа\",\"Parameter\":\"до 2\"},{\"Indicator\":\"Диаметр очищаемых трубопроводов, мм\",\"Parameter\":\"50 – 300\"},{\"Indicator\":\"Тип топлива\",\"Parameter\":\"дизель\"},{\"Indicator\":\"Вместимость цистерны, м3\",\"Parameter\":\"11,0\"},{\"Indicator\":\"Длина, мм\",\"Parameter\":\"8000-12100\"},{\"Indicator\":\"Ширина, мм\",\"Parameter\":\"2950-3440\"},{\"Indicator\":\"Высота, мм\",\"Parameter\":\"3200\"}]",
                            Description = "Основная задача работы комбинированной дорожной машины заключается в удалении загрязнений, скапливающихся на поверхности проезжей части, стояночных площадей, территорий предприятий с асфальтовым и бетонным покрытием.\nТак же комбинированные дорожные машины используются для полива и увлажнения территорий и зеленых насаждений, что приводит к снижению запыленности воздуха, повышению влажности и созданию более комфортные условия для людей и окружающей среды.\nВ зимний период машина используется для  очистки территорий и дорожного полотна от свежевыпавшего снега.\n",
                            Path = "polivomoechnayaMashina.jpg",
                            Title = "КОМБИНИРОВАННЫЕ ДОРОЖНЫЕ МАШИНЫ"
                        },
                        new
                        {
                            Id = 2,
                            About = "ООО \"Северный Ветер\" предлагает услуги по вывозу КГО,ТСО.\nДля осуществления сбора, транспортирования и размещения на специализированном объекте твердых строительных и крупногабаритных  отходов, используется техника различного назначения.",
                            CarModels = "[{\"Indicator\":\"Базовое шасси\",\"Parameter\":\"МАЗ-5337\"},{\"Indicator\":\"Мощность двигателя\",\"Parameter\":\"240\"},{\"Indicator\":\"Вмесимость кузова полезная, м3\",\"Parameter\":\"8\"},{\"Indicator\":\"Масса загружаемых отходов, кг\",\"Parameter\":\"4000\"},{\"Indicator\":\"Полная масса, кг\",\"Parameter\":\"11000\"},{\"Indicator\":\"Масса спецоборудования, кг\\t\",\"Parameter\":\"1800\"},{\"Indicator\":\"Длина, мм\",\"Parameter\":\"6310\"},{\"Indicator\":\"Ширина, мм\",\"Parameter\":\"2500\"},{\"Indicator\":\"Высота, мм\",\"Parameter\":\"2970\"}]",
                            Description = "Отлично справляются с задачей по вывозу строительного и крупногабаритного мусора. Бункеровоз оборудован портальным механизмом для размещения на территории Заказчика, погрузки и перевозки бункера-накопителя объемом 8,0 куб. метров",
                            Path = "TwoBunkerTrucks.jpg",
                            Title = "БУНКЕРОВОЗЫ"
                        },
                        new
                        {
                            Id = 3,
                            About = "Для вывоза твёрдых строительных и крупногабаритных отходов ООО \"Северный Ветер\" предлагает мультилифт.",
                            CarModels = "[{\"Indicator\":\"Базовое шасси\",\"Parameter\":\"Мерседес-Бенц 1625\"},{\"Indicator\":\"Мощность двигателя\",\"Parameter\":\"250\"},{\"Indicator\":\"Вмесимость кузова полезная, м3\",\"Parameter\":\"27\"},{\"Indicator\":\"Масса загружаемых отходов, кг\",\"Parameter\":\"12000\"},{\"Indicator\":\"Полная масса, кг\",\"Parameter\":\"24000\"},{\"Indicator\":\"Масса спецоборудования, кг\",\"Parameter\":\"12000\"},{\"Indicator\":\"Длина, мм\",\"Parameter\":\"8000\"},{\"Indicator\":\"Ширина, мм\",\"Parameter\":\"2500\"},{\"Indicator\":\"Высота, мм\",\"Parameter\":\"3100\"}]",
                            Description = "Если вы занимаетесь строительством или ремонтом и скопилось очень много строительного и крупногабаритного мусора, то мы можем предложить МУЛЬТИЛЬФТ на базовом шасси Мерседес-Бенц 1625. Его бункер вмещает в себя объем 27 м. куб.",
                            Path = "multilift.jpg",
                            Title = "МУЛЬТИЛИФТ"
                        },
                        new
                        {
                            Id = 4,
                            About = "ООО \"Северный Ветер\" предлагает сотрудничество в сфере оказания услуг вакуумными машинами при проведении работ по откачке и вывозу всех видов канализационных стоков.машинами при проведении работ по откачке и вывозу всех видов канализационных стоков.",
                            CarModels = "[{\"Indicator\":\"Базовое шасси\",\"Parameter\":\"МАЗ-КО 523\"},{\"Indicator\":\"Мощность двигателя\",\"Parameter\":\"227\"},{\"Indicator\":\"Вмесимость цистерны, м3\",\"Parameter\":\"10\"},{\"Indicator\":\"Полная масса, кг\",\"Parameter\":\"18000\"},{\"Indicator\":\"Масса спецоборудования, кг\",\"Parameter\":\"10000\"},{\"Indicator\":\"Длина, мм\",\"Parameter\":\"6310\"},{\"Indicator\":\"Ширина, мм\",\"Parameter\":\"2500\"},{\"Indicator\":\"Высота, мм\",\"Parameter\":\"2970\"},{\"Indicator\":\"Стоимость услуги, р.\",\"Parameter\":\"от 2500\"}]",
                            Description = " Ассенизация – часто востребованная услуга в районах с частными застройками по очистке нечистот. Технология подразумевает работы по удалению жидких бытовых отходов (ЖБО).\nОбъем цистерн ассенизационных машин - 10 м. куб. и 11 м. куб.\nСтоимость откачки и вывоза зависит от вида выполняемых работ, удаленности объекта заказчика от очистных сооружений, объема и характера ЖБО.\nПеред тем, как заказать услугу ассенизатора, необходимо проконсультироваться со специалистом нашей компаннии.",
                            Path = "pumpingOutSepticTanks.jpg",
                            Title = "АССЕНИЗАТОР"
                        });
                });

            modelBuilder.Entity("NorthWind.Core.Entities.Services.ServiceView", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("MainImageName")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("ServiceId");

                    b.ToTable("ServiceViews");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            MainImageName = "Assenizator.png",
                            Title = "ОТКАЧКА ЖИДКИХ БЫТОВЫХ ОТХОДОВ"
                        },
                        new
                        {
                            ServiceId = 2,
                            MainImageName = "KGO.png",
                            Title = "ВЫВОЗ СТРОИТЕЛЬНОГО И КРУПНОГАБАРИТНОГО МУСОРА"
                        },
                        new
                        {
                            ServiceId = 3,
                            MainImageName = "PolivIOchistkaTerrityriy.png",
                            Title = "ПОЛИВ И ОЧИСТКА ТЕРРИТОРИЙ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
